version: '3.8'
services:
  redisdb:
    image: redis:latest
    ports:
      - '6379:6379'
    container_name: redis_db
  
  hotelapp:
    build:
      context: ./
      dockerfile: Dockerfile-app
    ports:
      - '8081:8080'
    container_name: hotel-api-v1