server:
    port: 8081
spring:
    datasource:
        url: jdbc:h2:mem:hoteldb
        username: root
        password: 1234
        driverClassName: org.h2.Driver
        initialization-mode: never
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
    session:
        store-type: redis
    redis:
        host: localhost
        port: 6379
logging:
  level:
    org:
      atmosphere: warn
